### ISSUE TITLE
GPU requirements for evaluating our pre-trained model

### ISSUE THREAD

**Issue by gruossomonica** [sabarim/STEm-Seg#8]
Hi, 
thanks for your interesting work. 
What are the GPU requirements for evaluating on DAVIS your pre-trained model? 
I tried on my notebook. I installed PyTorch 1.4 with CUDA 10.0 and I used a GTX 1060 with 6 GB memory. I got the following error:
`RuntimeError: CUDA out of memory. Tried to allocate 820.00 MiB (GPU 0; 5.94 GiB total capacity; 3.31 GiB already allocated; 734.06 MiB free; 4.60 GiB reserved in total by PyTorch)`
Looking forward to your reply.

Best Regards,
Monica Gruosso

**Comment by Ali2500** [comment]
Hello Monica,

I suspect that 6GB will not be enough. We ran our inference experiments on a 1080Ti with 11GB VRAM. Does the error occur inside the encoder/backbone or the decoder?

**Comment by gruossomonica** [comment]
Thanks for your quick reply. I agree that 6GB is probably not enough.
Here the complete error I obtained today:
```
Model configuration
  - Backbone type: R-101-FPN
  - Backbone frozen: Yes
  - Embedding head type: squeeze_expand_decoder
  - Embedding head channels: [256, 256, 128, 128]
  - Embedding dims: 4
  - Embedding dim mode: xyff
  - Embedding free dim stds: [0.3, 0.3]
  - Embedding head normalization: gn
  - Embedding head pooling type: avg
  - Seediness head type: squeeze_expand_decoder
  - Seediness head channels: [256, 256, 128, 128]
  - Seediness head normalization: gn
  - Seediness head pooling type: avg
  - Semseg head type: N/A
  - Output resize scale: 1.0

Performing inference for sequence 1/30
 36%|███████████████▌                           | 25/69 [00:39<01:09,  1.57s/it]
Traceback (most recent call last):
  File "stemseg/inference/main.py", line 313, in <module>
    main(parser.parse_args())
  File "stemseg/inference/main.py", line 287, in main
    track_generator.start(args.seqs)
  File "stemseg/inference/main.py", line 120, in start
    self.process_sequence(sequence, self.max_tracks[i])
  File "stemseg/inference/main.py", line 129, in process_sequence
    embeddings, fg_masks, multiclass_masks = self.do_inference(sequence)
  File "/media/monica/DATA/documenti/Monica/vos_approaches/STEm-Seg/stemseg/utils/timer.py", line 83, in wrap2
    output = f(*args, **kwargs)
  File "stemseg/inference/main.py", line 141, in do_inference
    inference_output = self.model(image_paths, subseq_idxes)
  File "/home/monica/miniconda3/envs/stemseg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/monica/miniconda3/envs/stemseg/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/media/monica/DATA/documenti/Monica/vos_approaches/STEm-Seg/stemseg/modeling/inference_model.py", line 132, in forward
    embedding_head_output = self._model.embedding_head(embedding_input_features).squeeze(0)
  File "/home/monica/miniconda3/envs/stemseg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/monica/DATA/documenti/Monica/vos_approaches/STEm-Seg/stemseg/modeling/embedding_decoder.py", line 127, in forward
    feat_map_4x = self.block_4x(feat_map_4x)
  File "/home/monica/miniconda3/envs/stemseg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/monica/miniconda3/envs/stemseg/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/monica/miniconda3/envs/stemseg/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/monica/miniconda3/envs/stemseg/lib/python3.7/site-packages/torch/nn/modules/normalization.py", line 226, in forward
    input, self.num_groups, self.weight, self.bias, self.eps)
  File "/home/monica/miniconda3/envs/stemseg/lib/python3.7/site-packages/torch/nn/functional.py", line 1706, in group_norm
    torch.backends.cudnn.enabled)
RuntimeError: CUDA out of memory. Tried to allocate 410.00 MiB (GPU 0; 5.94 GiB total capacity; 4.78 GiB already allocated; 380.69 MiB free; 4.87 GiB reserved in total by PyTorch)
```
I tested with my unlabeled images (few data) and works properly.

**Comment by Ali2500** [comment]
Seems to be in the decoder, so it'll be hard to split the computation. You could try reducing the resolution (`cfg.INPUT.MIN/MAX_DIM`) until you no longer get this error, but then the result quality will also be lower.

**Comment by gruossomonica** [comment]
Thank you.

Best Regards,
Monica Gruosso
